# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robert Aguilera
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Check out the art and design of Robert Aguilera, a casual creator based out of New York.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site
instagram_username: r3ciprocal
# github_username:  jekyll

# Build settings
markdown: kramdown


plugins:
  - jekyll-paginate
  - jekyll-compose

paginate: 6
paginate_path: "blog/page:num"
